blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from .views import *

app_name = BlogConfig.name

urlpatterns = [
    path('article/', ArticleListView.as_view(), name='article_list'),
    path('article/new/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Article(models.Model):
    name = models.CharField(max_length=300, verbose_name="заголовок")
    description = models.TextField(verbose_name="содержимое")
    photo = models.ImageField(
        upload_to="blog/photo", verbose_name="Превью", blank=True, null=True
    )
    created_at = models.DateTimeField(verbose_name="дата создания", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="признак публикации", auto_now=True)
    views_counter = models.PositiveIntegerField(
        verbose_name="количество просмотров", default=0
    )


class Meta:
    verbose_name = "Модель"
    verbose_name_plural = "Модели"


def __str__(self):
    return self.name

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from blog.models import Article


class ArticleCreateView(CreateView):
    model = Article
    fields = ["name", "description", "photo"]
    template_name = "blog/article_form.html"
    success_url = reverse_lazy("blog:article_list")


class ArticleListView(ListView):
    model = Article
    template_name = "blog/article_list.html"
    context_object_name = "articles"


class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/article_detail.html"
    context_object_name = "article"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ["name", "description", "photo"]
    template_name = "blog/article_form.html"
    success_url = reverse_lazy("blog:article_list")

    def get_success_url(self):
        return reverse("blog:article_detail", args=[self.kwargs.get("pk")])


class ArticleDeleteView(DeleteView):
    model = Article
    template_name = "blog/article_confirm_delete.html"
    success_url = reverse_lazy("blog:article_list")

blog/templates/blog/article_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма Blog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-text">Удалить Blog</h2>
                    <p>Вы уверены, что хотите удалить Blog "{{ article.name }}" ?</p>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div>

                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a class="btn btn-warning" href="{% url 'blog:article_list'%}" role="button">Отмена</a>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/article_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма Blog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-text">{{ article.name }}</h2>
                    <p>{{ article.description }}</p>
                    <p>{{ article.photo }}</p>
                    <p>Создано: {{ article.created_at }}</p>
                    <p>Обновлено: {{ article.updated_at }}</p>
                    <p>Количество просмотров: {{ article.views_counter }}</p>
                    <a class="btn btn-outline-primary" href="{% url 'blog:article_list'%}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/article_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма Blog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <h1 class="mb-4">Blog</h1>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div>

                            <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                            <a class="btn btn-outline-dark" href="{% url 'blog:article_list'%}" role="button">Отмена</a>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/article_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма Blog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-text">Blog</h1>
                    <a class="btn btn-outline-success btn-lg" href="{% url 'blog:article_create' %}" role="button">Создать новый Blog</a>

                    <ul class="list-group">
                        {% for article in articles %}
                        <li class="list-group-item">
                            <a class="btn btn-outline-primary" href="{% url 'blog:article_detail' article.pk %}" role="button">{{ article.name }}</a>
                            <a class="btn btn-outline-dark" href="{% url 'blog:article_update' article.pk %}" role="button">Редактировать</a>
                            <a class="btn btn-outline-danger" href="{% url 'blog:article_delete' article.pk %}" role="button">Удалить</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>