blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from .views import *

app_name = BlogConfig.name

urlpatterns = [
    path('article/', ArticleListView.as_view(), name='article_list'),
    path('article/new/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from .views import *
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),

    path('product/', ProductListView.as_view(), name='products_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:product_id>/unpublish', UnpublishProductView.as_view(), name='unpublish_product'),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from .views import *

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import forms

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    avatar = models.ImageField(upload_to='user/avatars', verbose_name='аватар', blank=True, null=True)
    phone_number = models.CharField(max_length=15, verbose_name='номер телефона', blank=True, null=True)
    country = models.CharField(max_length=200, verbose_name='Страна', blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError('Номер телефона должен состоять только из цифр')
        return phone_number

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from catalog.forms import StyleFormMixin
from users.models import User




class UsersForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")

users/views.py
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic.edit import *
from django.contrib.auth import login

from users.forms import UsersForm
from users.models import User

from config.settings import EMAIL_HOST_USER

class UserCreateView(CreateView):
    model = User
    form_class = UsersForm
    success_url = reverse_lazy("users:login")


    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.send_welcome_email(user.email)
        return super().form_valid(form)

    def send_welcome_email(self, user_email):
        subject = 'Добро пожаловать в наш сервис'
        message = 'Спасибо, что зарегистрировались в нашем сервисе!'
        from_email = EMAIL_HOST_USER
        recipient_list = [user_email]
        send_mail(subject, message, from_email, recipient_list)

users/templates/users/user_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма NewModel</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                          <div class="card-body">
                          {% csrf_token %}
                          {{ form.non_field_errors }}
                          {{ form.as_p }}
                          <button type="submit" class="btn btn-outline-primary">
                              Регистрация
                          </button>
                          <a class="btn btn-outline-dark" href="{% url 'catalog:products_list' %}" role="button">Назад</a>
                          </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>
{% endblock %}