blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from .views import *

app_name = BlogConfig.name

urlpatterns = [
    path('article/', ArticleListView.as_view(), name='article_list'),
    path('article/new/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from .views import *
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),

    path('product/', ProductListView.as_view(), name='products_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:product_id>/unpublish', UnpublishProductView.as_view(), name='unpublish_product'),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from users.models import User

class NewModel(models.Model):
    name = models.CharField(max_length=300, verbose_name="заголовок")
    description = models.TextField(verbose_name="содержимое")
    photo = models.ImageField(upload_to="newmodel/photo", verbose_name="Превью", blank=True, null=True)
    created_at = models.DateTimeField(verbose_name="дата создания", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="признак публикации", auto_now=True)
    views_counter = models.PositiveIntegerField(verbose_name='количество просмотров', default=0)

    class Meta:
        verbose_name = "Модель"
        verbose_name_plural = "Модели"


    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name="наименование продукта")
    description = models.TextField(verbose_name="описание продукта", blank=True, null=True)
    photo = models.ImageField(upload_to="product/photo", verbose_name="Фото продукта", blank=True, null=True)
    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        verbose_name="категория",
        blank=True,
        null=True,
        related_name="products",
    )
    price = models.IntegerField(verbose_name="цена за покупку")
    created_at = models.DateTimeField(verbose_name="дата создания", auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(verbose_name="дата последнего изменения", auto_now=True, blank=True, null=True)
    views_counter = models.PositiveIntegerField(verbose_name='количество просмотров', default=0)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Владелец')
    publish_product = models.BooleanField(default=True, blank=True, null=True)


    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['category', 'name']
        permissions = [
            ('can_unpublish_product', 'Can unpublish product')
        ]

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name="наименование категории")
    description = models.TextField(verbose_name="описание категории", blank=True, null=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

catalog/forms.py
from django.forms import ModelForm, BooleanField
from django.core.exceptions import ValidationError

from catalog.models import Product


taboo_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance( field, BooleanField):
                field.widget.attrs['class'] = "form-check-input"
            else:
                field.widget.attrs['class'] = "form-control"


class CatalogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ("views_counter",)

class CatalogAdminForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ("publish_product",)

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0:
            raise ValidationError ('Цена продукта не может быть отрицательной')
        return price

    def clean_name(self):
        name = self.cleaned_data.get('name')
        for word in taboo_words:
            if word in name.lower():
                raise ValidationError ('Это запрещенные слова, которые нельзя использовать в названиях продуктов')
        return name


    def clean_description(self):
        description = self.cleaned_data.get('description')
        for word in taboo_words:
            if word in description.lower():
                raise ValidationError ('Это запрещенные слова, которые нельзя использовать в описаниях продуктов')
        return description

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
from django.views.generic import View
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from catalog.services import get_product_cache

from catalog.forms import CatalogForm, CatalogAdminForm
from catalog.models import Product


def home(request):
    return render(request, "home.html")


def contacts(request):
    if request.method == "POST":
        name = request.POST.get("name")
        message = request.POST.get("message")
        return HttpResponse("Данные отправлены.")
    return render(request, "contacts.html")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = CatalogForm, CatalogAdminForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:products_list")

    def form_valid(self, form):
        self.object = form.save()
        user = self.request.user
        self.object.owner = user
        self.object.save()
        return super().form_valid(form)

class ProductListView(ListView):
    model = Product
    template_name = "catalog/product_list.html"
    context_object_name = "products"

    def get_queryset(self):
        return get_product_cache()

class ProductDetailView(DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = CatalogForm, CatalogAdminForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:product_list")

    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return CatalogForm
        if user.has_perm('catalog.can_unpublish_product'):
            return CatalogAdminForm
        raise PermissionDenied

    def get_success_url(self):
        return reverse("catalog:product_detail", args=[self.kwargs.get("pk")])

class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    form_class = CatalogForm, CatalogAdminForm
    template_name = "catalog/product_confirm_delete.html"
    success_url = reverse_lazy("catalog:products_list")

    def test_func(self):
        user = self.request.user
        return user == self.object.owner or user.has_perm('catalog.can_delete_product')

    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super().form_valid(form)

class UnpublishProductView(LoginRequiredMixin, View):
    def post(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        if not request.user.has_perm('catalog.can_unpublish_product'):
            return PermissionDenied

        product.unpublish = product.is_active
        product.is_active = False
        product.save()
        return redirect('catalog:product_detail', product_id=product.id)

catalog/templates/catalog/product_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
    <div class="container">
      <div class="row">
        <div class="col">
          <form class="row" method="post" enctype="multipart/form-data">
            <div class="card">
                <p class="card-text">Вы действительно хотите удалить "{{ object.name }}" ?</p>
              <div class="card-body">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-outline-danger">Удалить</button>
                  <a class="btn btn-outline-dark" href="{% url 'catalog:products_list' %}" role="button">Отмена</a>

              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ product.photo | media_filter }}" class="img-thumbnail">
            <div class="card-body">
                <p class="card-text">{{ product.name }}</p>
                <p class="card-text">Цена: {{ product.price }}</p>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text">{{ product.category }}</p>

                {% if "catalog.can_unpublish_product" in perms %}
                    <form action="{% url 'catalog:unpublish_product' product.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary">Отмена публикации</button>
                    </form>
                {% endif %}
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-outline-dark" href="{% url 'catalog:products_list' %}" role="button">Назад</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Форма NewModel</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
<div class="container">
  <div class="row">
    <div class="col">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
          <div class="card-body">
              {% csrf_token %}
              {{ form.non_field_errors }}
              {{ form.as_p }}
              <button type="submit" class="btn btn-outline-primary">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
              </button>
              <a class="btn btn-outline-dark" href="{% url 'catalog:products_list' %}" role="button">Назад</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ product.photo | media_filter }}" class="img-fluid">
            <div class="card-body">
              <p class="card-text"> {{ product.name }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-outline-dark" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробно</a>
                    {% if perms.catalog.can_unpublish_product or user == product.owner %}
                    <a class="btn btn-outline-warning" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-outline-danger" href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить</a>
                    {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}